# Generated by Django 4.2 on 2026-04-30 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_recepcao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pessoa',
            table='usuarios',
        ),
    ]
